language: bash
sudo: require
dist: trusty

script:
  - bash -ex build.sh

after_success:
  - sudo apt-get -y install maven
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./out/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
